### ISSUE TITLE
'bbox_pred' layer shape mismatch when loading the pretrained model from autoloc_iter_200.caffemodel

### ISSUE THREAD

**Issue by JacobKong** [zhengshou/AutoLoc#3]
Dear author:
I got shape mismatch error when loading the pretrained model from your autoloc_iter_200.caffemodel.
The error is:
`F1227 23:08:33.047071 149335 net.cpp:759] Cannot copy param 0 weights from layer 'bbox_pred'; shape mismatch.  Source param shape is 26 128 1 1 (3328); target param shape is 12 128 1 1 (1536). To learn this layer's parameters from scratch rather than copying from a saved net, rename the layer.`

The num_output of layer 'bbox_pred' is calculated by `2 * len(cfg.TRAIN.ANCHOR_SCALES)` and should be `12*128*1*1`, but the given shape from the caffemodel is `26*128*1*1`. Maybe you train the model with 13 anchors not 6 anchors that reported in the config.

So how to fix this problem?

**Comment by zhengshou** [comment]
Thanks for the heads-up. I will take a look.

**Comment by JacobKong** [comment]
Dear author:

Have you come up any idea about this issue😊?

**Comment by zhengshou** [comment]
Updated with the correct models. Please check. Thanks.

**Comment by zhengshou** [comment]
also let me know if you come across similar problems for AN models

**Comment by JacobKong** [comment]
I'll, thanks a lot！
